### ISSUE TITLE
should we support dynamic openxr runtime loading with windows registry

### ISSUE THREAD

**Issue by kcking** [Ralith/openxrs#103]
The registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenXR\1 ActiveRuntime` can be set to indicate the default openxr runtime on windows. It seems like openxr-sys would be the place to implement that behavior -- perhaps enabled with a feature?

I wanted to float this here before actually implementing it.

**Comment by Ralith** [comment]
That behavior is implemented in the OpenXR loader, which is what this crate binds to.

**Comment by kcking** [comment]
Ah thanks I see that now :)
