### ISSUE TITLE
Vulkan Submission

### ISSUE THREAD

**Issue by hodasemi** [Ralith/openxrs#11]
Hi, 

I got a problem with displaying my submitted Vulkan images. I have done as you did in your OpenGL example (except with a Vulkan setup): 
https://github.com/hodasemi/Context/blob/c3d528cd53ace9f46b0b9c6854b6d0eac1c9f6f1/presentation/src/xri/openxrrendercore.rs#L429. Then I looked for Vulkan examples and I found xrgears and took its approach of using separate swapchains for each eye, but the result is the same.

When nothing is being rendered, the left side should just be green and the right side just red, because I'm just clearing the images (https://github.com/hodasemi/Context/blob/c3d528cd53ace9f46b0b9c6854b6d0eac1c9f6f1/presentation/src/renderbackend.rs#L186), but instead the screen is just black.

If I enable the renderdoc vulkan device extension, the left part of the screen is getting rendered, but with a green color, which should actually be on the right side.

So my question is, if you did experience any similar issues?
If not, could you help me, finding my issue?

**Comment by Ralith** [comment]
One problem is that you're erroneously passing in the swapchain image index to `SwapchainSubImage::image_array_index`. The swapchain image index is propagated implicitly; you don't need to pass it in anywhere. `image_array_index` identifies which *layer* of an *array* swapchain to use, whereas you're not using an array swapchain at all. Try leaving that value at 0.

**Comment by hodasemi** [comment]
Oh yea, thanks.
But the result is still the same with nothing displayed.

If you want to take a look yourself: https://github.com/hodasemi/LightFieldVRViewer/tree/OpenXR 
Use the OpenXR branch.

**Comment by Ralith** [comment]
What runtime are you using? Also, renderdoc tends to get confused by VR unless you use [the in-application API](https://renderdoc.org/docs/in_application_api.html) to explicitly designate the Vulkan instance and submissions you care about.

**Comment by hodasemi** [comment]
I am using Monado (https://gitlab.freedesktop.org/monado/monado).

I didn't know that about renderdoc ...

**Comment by Ralith** [comment]
Monado is fairly buggy and incomplete, so it can be difficult to determine whether an issue is your app's fault. I recommend making sure the vulkan validation layers are enabled and validating your application's logic with renderdoc, then looking for misbehavior in Monado itself.

**Comment by hodasemi** [comment]
I found the error on my side, which was rather stupid. A little copy paste error, where I used the left swapchain for both the left and the right eye.

Sorry for any inconveniences.

**Comment by Ralith** [comment]
No worries, glad you got it working!
