### ISSUE TITLE
Creating Entry from pointer to xrGetInstanceProcAddr

### ISSUE THREAD

**Issue by CodeWitchBella** [Ralith/openxrs#116]
I'm currently experimenting with creating unity plugin, which hooks into openxr runtime. This works by providing unity with a function which takes pointer to xrGetInstanceProcAddr and returning my own pointer xrGetInstanceProcAddr. This means that I can override any function I want.

I am using openxr_sys for this and it is a big help 🙂 However, I'd like to try to use the safe wrapper for some parts, but I am unable to construct Entry, because I do not want to statically, nor dynamically load anything - this is already handled by Unity. Would you be open to a PR, which would add new way to construct Entry?

It would look something like this

```rust
    pub fn from_get_instance_proc_addr(func: sys::pfn::GetInstanceProcAddr) -> Result<Self> {
        // ...
    }
```

**Comment by Ralith** [comment]
Sure, though I think that should be `unsafe`, since there are very specific requirements on the behavior of the `func`.
