### ISSUE TITLE
Loader structs

### ISSUE THREAD

**Issue by Supreeeme** [Ralith/openxrs#123]
Would there be a chance of getting the loader structs into openxr_sys? They aren't listed in the registry but they are here: https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/main/src/common/loader_interfaces.h

These are necessary for writing API layers.

**Comment by Ralith** [comment]
I just merged https://github.com/Ralith/openxrs/pull/120 which adds these.

**Comment by Supreeeme** [comment]
A new release sooner would definitely be appreciated :)

**Comment by Ralith** [comment]
Published 0.17.
