### ISSUE TITLE
XR_FB_eye_tracking_social

### ISSUE THREAD

**Issue by WuZemyp** [Ralith/openxrs#140]
Hello, I would like to ask whether it can support the openxr extension XR_FB_eye_tracking_social ?. I found the bool variable in avaliable extension side but where is the source code for eye_trakcing_social ？
Thank you!

**Comment by Ralith** [comment]
Nobody's written high-level bindings for that, but you should be able to use the raw -sys bindings.

**Comment by zarik5** [comment]
[ALVR](https://github.com/alvr-org/ALVR/blob/2b17f057a069f56927047e38c4c2c18a5e24e33b/alvr/client_openxr/src/lib.rs) is successfully using XR_FB_eye_tracking_social for a while, using a [fork of openxrs](https://github.com/alvr-org/openxrs/commits/master). Unfortunately I don't have the time to finish a PR, there were issues in the generated files and I manually patched them for now.
