### ISSUE TITLE
cargo run --bin generator fails with "4X4_50" is not a valid Ident

### ISSUE THREAD

**Issue by mrao** [Ralith/openxrs#153]
While regenerating the rust binding starting OpenXR SDK commit id 77a93e7e01854a6614c790f78bef87745562faae, script fails with above error in thread 'main' panicked at generator/src/main.rs:2145:5.

**Comment by Ralith** [comment]
Is that addressed by #147?

**Comment by Ralith** [comment]
Looks like something that can be easily addressed in whatever PR pursues that update.

**Comment by mrao** [comment]
Thank you Ralith
