### ISSUE TITLE
openxr::FrameStream::end returns `Result<()>`

### ISSUE THREAD

**Issue by VZout** [Ralith/openxrs#16]
`openxr::FrameStream::end` returns an result without an error. The C++ API of OpenXR actually returns a XrResult.

I'm currently having an issue where the result returned by `openxr::FrameStream::end` is the `Err()` variant but I don't know why because there is no error telling me why it failed.

Is there a specific reason this function doesn't return a result with a error like `create_session`?

**Comment by Ralith** [comment]
`openxr::Result<T>` [is shorthand for](https://docs.rs/openxr/0.11.0/openxr/type.Result.html) `std::result::Result<T, openxr::sys::Result>`. That means the `Err` variant contains a [`openxr::sys::Result`](https://docs.rs/openxr-sys/0.7.2/openxr_sys/struct.Result.html), which will indeed tell you why it failed. Try formatting it!

**Comment by VZout** [comment]
Damn for some reason I thought it was `std::result::Result<T, T>`
