### ISSUE TITLE
0.19.0 Release

### ISSUE THREAD

**Issue by msub2** [Ralith/openxrs#165]
Would you be able to cut a new release to be able to use some of the extensions introduced in OpenXR 1.0.34? I'm starting to update Servo's WebXR crate, specifically its OpenXR input handling, and there's some controller extensions I need like `XR_META_touch_controller_plus` that aren't available in 0.18.0.

**Comment by Ralith** [comment]
Sure, I'll try to push it out this week.

**Comment by Ralith** [comment]
Published 0.19, with OpenXR 1.0.36.
