### ISSUE TITLE
Support arbitrary extensions

### ISSUE THREAD

**Issue by Manishearth** [Ralith/openxrs#17]
More extensions will continue to be added; the `ExtensionSet` struct should contain an open ended `Vec<String>` for extensions that are unknown to this API.

**Comment by Ralith** [comment]
I'll see about adding this, but in the meantime you can always call the raw unsafe function pointers via `entry.fp()`, and then use `Instance::from_raw` to get back into safe land.

**Comment by Ralith** [comment]
Fixed by #18.
