### ISSUE TITLE
When I enable the ext_hand_tracking extension, it seems to cause a memory corruption or pointer error

### ISSUE THREAD

**Issue by xujunjie12345** [Ralith/openxrs#175]
When using ALVR 20.6.1 on the gen1 platform based on qcom algorithms, everything works normally. However, when I enable the ext_hand_tracking extension, calling xrGetActionStatePose results in an XR_ERROR_PATH_UNSUPPORTED error. Additionally, I noticed that the isActive field of XrActionStatePose is a random number, such as -651485936. 

Therefore, I suspect there might be issues like memory corruption or pointer errors

**Comment by Ralith** [comment]
Dup of https://github.com/Ralith/openxrs/issues/169.
