### ISSUE TITLE
Unable to find libs/arm64-v8a vs libunwind

### ISSUE THREAD

**Issue by kvark** [Ralith/openxrs#181]
Compiling with NDK-r21 I'm getting "-lunwind" not found. Based on [this page](https://blog.rust-lang.org/2023/01/09/android-ndk-update-r25.html), I need to use  a newer NDK. If I go with NDK-r25, I get this error during build:
> Error: IoError on `"C:\\Code\\openxrs\\openxr\\examples/libs\\arm64-v8a"`: The system cannot find the path specified. (os error 3)

If I copy this libs folder from NDK-r21r, I'm getting this:
```
12-14 19:24:27.400 11989 12019 I RustStdoutStderr: thread '<unnamed>' panicked at openxr\examples/vulkan.rs:39:14:
12-14 19:24:27.400 11989 12019 I RustStdoutStderr: couldn't find the OpenXR loader; try enabling the "static" feature: DlOpen { desc: "dlopen failed: library \"libopenxr_loader.so\" not found" }
12-14 19:24:27.400 11989 12019 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
12-14 19:24:27.402 11989 11989 I VrosSpatialAudio: init with android.view.ViewRootImpl$W@e5f4544
```

**Comment by kvark** [comment]
Looks like NDK-r23 solves the libunwind issue and also carries "arm64-v8a".
However, the build process doesn't find this "libs/arm65-v8a" folder. Must be some special env var I'm missing

**Comment by kvark** [comment]
It's a bit of a mixed bag of an issue. The stuff about "libopenxr_loader.so" is preceded with this warning that could be relevant:
> 12-14 19:24:27.365 11989 11989 W System  : ClassLoader referenced unknown path:
12-14 19:24:27.366 11989 11989 W linker  : Warning: unable to resolve "/apex/com.meta.xr/priv-app/VrDriver/VrDriver.apk": No such file or directory (ignoring)

**Comment by kvark** [comment]
Ah, I see that README actually talks about this:
> Get `libopenxr_loader.so` from the Oculus OpenXR Mobile SDK and add it to `openxr/examples/libs/arm64-v8a`

**Comment by Ralith** [comment]
Is there any action needed for us here?

**Comment by kvark** [comment]
I think the readme needs to be fixed. It's only saying
> * Get `libopenxr_loader.so` from the Oculus OpenXR Mobile SDK and add it to `openxr/examples/libs/arm64-v8a`

But it's not saying how this "libs" folder needs to appear in the first place. It's not a part of the repo.

**Comment by Ralith** [comment]
Want to make a PR? I don't have any expertise on the Android side of things.

**Comment by kvark** [comment]
Ok, will do
