### ISSUE TITLE
OpenGL session creation info is missing for Win32

### ISSUE THREAD

**Issue by jdm** [Ralith/openxrs#2]
The low-level bindings exist, but the higher level bindings are missing. If nobody else gets to it first, we will create these as part of the OpenXR work that Servo is doing for HoloLens.

**Comment by Ralith** [comment]
That would be great! I've been reluctant to bang them (and the DirectX bindings) out myself since it's not presently convenient for me to test on Windows.

**Comment by Ralith** [comment]
I believe this was fixed by #4.
