### ISSUE TITLE
Implement common traits for various structs

### ISSUE THREAD

**Issue by Manishearth** [Ralith/openxrs#25]
It would be nice if things like Fovf and Posef implemented traits like `PartialEq` and `Default`.

**Comment by Ralith** [comment]
This turns out to be annoying to do due to raw pointers and large arrays preventing derives for these.

**Comment by Manishearth** [comment]
@Ralith well, sure, we should do this for the value types like Posef and Fovf, we don't have to do it for more complex objects.

**Comment by Ralith** [comment]
Folded a draft into #30 based on doing the laziest thing possible.

**Comment by Ralith** [comment]
Are there any useful cases still missing, or should we consider this more or less solved?
