### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by rpavlik** [Ralith/openxrs#26]
https://github.com/Ralith/openxrs/blob/6dc9cf027e10ecd4e885c35c49840d9cda9a54c0/generator/src/main.rs#L31

Was looking and wanted to comment on this - the leading "garbage" is in fact the "byte order mark" which keeps getting added and removed as people edit it. I have not yet found a convenient way to forcible add or remove it, but your upstream for file loading might consider handling it because some editors are apparently adding it automatically.

**Comment by Ralith** [comment]
Seems like this has stayed gone for a while now. If it comes back I'll probably add a dynamic check, or maybe propose that the XML people do it; rust's filesystem ops are not text-specific so it wouldn't really belong there.

**Comment by rpavlik** [comment]
Yeah somebody contributed a script that removes it which I've run before each release 😁
