### ISSUE TITLE
Api layers are not exposed

### ISSUE THREAD

**Issue by MaikKlein** [Ralith/openxrs#27]
I am currently trying to enable API layers, but I noticed that this is not exposed in OpenXR.

https://github.com/Ralith/openxrs/blob/master/openxr/src/entry.rs#L142-L143

Is there a reason for this?

I am currently tracking down some validation errors, but the debug message callback is almost printing nothing by default. I assume there might be some validation layers that would help me.

**Comment by Ralith** [comment]
These aren't exposed because I haven't put any effort into defining a high-level interface for them, though on review `&[&str]` would probably do fine. In the mean time, you could set the `XR_ENABLE_API_LAYERS` environment variable,

**Comment by Ralith** [comment]
Can I get your review on https://github.com/Ralith/openxrs/pull/28?
