### ISSUE TITLE
Vulkan example doesn't run on Linux

### ISSUE THREAD

**Issue by Masterchef365** [Ralith/openxrs#40]
Running the Vulkan example with:
```shell
export VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation
cargo run --example vulkan --features static >log.txt
```
Does not display to the HMD and instead appears to hang in SteamVR. See attached error messages from validation layers in [log.txt](https://github.com/Ralith/openxrs/files/5080252/log.txt)
Note that the same trial did work on Windows on the same computer (albeit with different validation layer errors).
OpenXR runtime for both Windows and Linux trials: SteamVR beta 1.14.6
Operating system: Ubuntu Linux 20.04
Graphics card: NVidia GTX 1070
Driver version: 440.100
HMD: Original Vive

**Comment by Ralith** [comment]
Those validation errors are due to bugs in SteamVR (see e.g. https://steamcommunity.com/app/250820/discussions/8/2448217690501186600/). Given that the example works fine against Monado, I'm guessing the lack of an image on the display is fallout from those bugs.

**Comment by Masterchef365** [comment]
Ah, that makes sense. I'll try under Monado!
