### ISSUE TITLE
OpenXR-sys fails to compile the OpenXR SDK on Arch Linux

### ISSUE THREAD

**Issue by Masterchef365** [Ralith/openxrs#41]
The `build.rs` script seems to have have an issue configuring `cmake` where `jsoncpp` is left out somehow. Compiling with `cargo check --features static` results in the following excerpt:
```
CMake Error: install(EXPORT "openxr_loader_export" ...) includes target "openxr_loader" which requires target "jsoncpp_interface" that is not in any export set.
CMake Error in src/loader/CMakeLists.txt:
  export called with target "openxr_loader" which requires target
  "jsoncpp_interface" that is not in any export set.
```
Using the OpenXR SDK's `README.md` instructions to compile the `OpenXR-SDK` folder that `openxr-sys` clones works just fine, which leads me to believe the issue is in `build.rs` somehow.

**Comment by Ralith** [comment]
I cannot reproduce this. Is the submodule up to date? Is your cmake reasonably current?

**Comment by Masterchef365** [comment]
My CMake version is 3.17.3, and I did make sure to run `git submodule update --recursive` before compiling. I'll try to find a way to reproduce this issue; didn't know if it might be something you already knew about.

**Comment by Masterchef365** [comment]
Looks like it's actually an issue compiling the OpenXR SDK statically on Arch (reproducible with the `-DDYNAMIC_LOADER=OFF` option on a fresh install of Manjaro).

**Comment by Ralith** [comment]
Interesting, thanks for investigating further! I've got cmake 3.16.3 so that should be fine. It looks like jsoncpp is vendored inside the SDK, so this smells like an upstream build system issue that doesn't manifest in my environment. I suggest opening an issue at https://github.com/KhronosGroup/OpenXR-SDK-Source.

**Comment by Masterchef365** [comment]
For others who might see this later, it turns out there's an AUR package (openxr-loader-git) which :sparkles: just works :sparkles: so I'll be using that. Cheers!

**Comment by Ralith** [comment]
On Linux it's best practice to favor dynamic linking like that anyway, since then the distro/whatever can update the loader and your app will benefit.
