### ISSUE TITLE
How does the openxr-sys generation layer handle memory allocation for return values?

### ISSUE THREAD

**Issue by str4d** [Ralith/openxrs#54]
Using a specific function as an example:

The [OpenXR specification](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#xrGetVulkanGraphicsDeviceKHR) states that for valid usage of `xrGetVulkanGraphicsDeviceKHR`, `vkPhysicalDevice` must be a pointer to a `VkPhysicalDevice` value to be populated. However, `openxr::Instance::vulkan_graphics_device` passes in `std::ptr::null()`:

https://github.com/Ralith/openxrs/blob/8caef1498c832db61c81ceff5c42fd7e955a30b3/openxr/src/instance.rs#L223-L232

This suggests that there is an intermediate Rust layer that allocates the required memory for `VkPhysicalDevice`, and sets `&mut out` to point to it. What I can't figure out is, where is the memory allocated?

**Comment by Ralith** [comment]
> However, openxr::Instance::vulkan_graphics_device passes in std::ptr::null():

This is incorrect. The code you cited is passing in a pointer *to a variable on the stack*, which initially contains null. That variable is, on success, overwritten by the OpenXR implementation. There is no heap allocation.

**Comment by str4d** [comment]
Yes, it's passing an `&mut VkPhysicalDevice`, which per `openxr-sys` is a typedef for `&mut *const c_void`, which is not a C-repr struct. So when I read:
> `vkPhysicalDevice` is a pointer to a `VkPhysicalDevice` value to populate.

in the OpenXR spec, I should read that as "a pointer to a pointer"? And the OpenXR runtime sets it to be a pointer to the actual structure in its memory?

**Comment by str4d** [comment]
Ahh, I see: the Vulkan spec defines `VkPhysicalDevice` as simply a handle, so its structure _is_ a pointer.
