### ISSUE TITLE
Locate views pose delay/duplicate frames steamvr

### ISSUE THREAD

**Issue by GitHubJasper** [Ralith/openxrs#56]
I am trying to use my vive to run a simple scene with a few triangles.
While I got it al working it feels like 1 in 3 frames lag behind, even though the chaperone does update correctly.
The fps is good (around 90) and when I animate the triangles by just updating their position, it all looks smooth
Turning or moving the headset just causes horrible stutters.

This might not be an issue with openxrs, I just don't know where to start looking for a solution.
There were some problems getting steamvr to work, I decided to just filter out 'VK_EXT_debug_marker' from the required device extensions. (not sure if this causes any issues but at least it runs this way)

Maybe someone can point me in the right direction?
Could be that this is just an issue with the openxr implementation of steam vr, but didn't see anyone else with the same issue...
Could also be an issue with my code as I am not really experienced in writing engine code.
This is the what I use to get the view projection matrix:
```
  pub fn get_vp(view: &View, project: &glm::Mat4x4) -> [[f32; 4]; 4] {
    let orient = view.pose.orientation;
    let orient_glm = glm::quat(orient.x, orient.y * -1.0, orient.z, orient.w * -1.0);
    let rotation = &glm::quat_cast(&glm::quat_inverse(&orient_glm));

    let position = view.pose.position;
    let position_glm = glm::vec3(position.x, -position.y, position.z);
    let translation = glm::inverse(&glm::translation(&position_glm));
    
    let view_matrix = rotation * translation;
    let vp = project * view_matrix;
    vp.into()
  }
```

Any help would be much appreciated!!

**Comment by Ralith** [comment]
Are you passing the correct time to `locate_views`? Are you storing your results in the correct uniform buffer, and synchronizing access to that buffer properly? Are you running a release build of your program?

> There were some problems getting steamvr to work, I decided to just filter out 'VK_EXT_debug_marker' from the required device extensions. (not sure if this causes any issues but at least it runs this way)

This is a known bug in SteamVR.

**Comment by GitHubJasper** [comment]
Thanks for the response!

I have tried both release and debug, doesn't make a difference
Use the `predicted_display_time` same as in the example.

It could be the buffer, because I have not written such low level code before.
I use `vk_mem` to create a uniform buffer with CpuToGpu memory usage.
And write to it like this:
```
let data_ptr = allocator.map_memory(&self.allocation)? as *mut T;
unsafe {
   data_ptr.copy_from_nonoverlapping(data.as_ptr(), data.len())
};
allocator.unmap_memory(&self.allocation)?;
```

This is the vertex shader:
```
#version 450
#extension GL_EXT_multiview : require
#extension GL_ARB_separate_shader_objects : enable

layout(location = 0) in vec3 position;
layout(location = 0) out vec2 screen_coords;

layout(binding = 0) uniform RightEye {
    mat4 mvp;
} right;
layout(binding = 1) uniform LeftEye {
    mat4 mvp;
} left;

void main()  {
    screen_coords = vec2((gl_VertexIndex << 1) & 2, gl_VertexIndex & 2);
    if (gl_ViewIndex == 1) {
        gl_Position = left.mvp *vec4(position, 1.0f);
    } else {
        gl_Position = right.mvp * vec4(position, 1.0f);
    }
}
```

**Comment by Ralith** [comment]
Are you only using a single buffer? How are you synchronizing access to it?

**Comment by GitHubJasper** [comment]
I use two buffers, one for each eye.
Between the two eyes they are synchronized, but maybe you mean when buffer is written and the frame is rendered?

I am not sure how I would synchronize that though, didn't see anything about it in the [vulkan tutorial](https://vulkan-tutorial.com/Uniform_buffers/Descriptor_layout_and_buffer). They just copy and leave it there. How would you synchronize it, using memory barriers?

Don't know if this helps but these are the descriptors for the buffers:
```
let descriptorset_layout_binding_descs = [
    vk::DescriptorSetLayoutBinding::builder()
      .binding(0)
      .descriptor_type(vk::DescriptorType::UNIFORM_BUFFER)
      .descriptor_count(1)
      .stage_flags(vk::ShaderStageFlags::VERTEX)
      .build(),
    vk::DescriptorSetLayoutBinding::builder()
      .binding(1)
      .descriptor_type(vk::DescriptorType::UNIFORM_BUFFER)
      .descriptor_count(1)
      .stage_flags(vk::ShaderStageFlags::VERTEX)
      .build()
  ];
```

**Comment by Ralith** [comment]
There are lots of ways to synchronize things. The CPU -> GPU dependency is handled by the implicit barrier on submit. However, you also need to ensure that the CPU doesn't write the next data while the GPU's still reading the previous data. The easiest way to do this is by targeting a certain number of frames in flight (typically 2), giving each its own set of buffers, and waiting on the submission fence for each frame before writing to its buffer.

**Comment by GitHubJasper** [comment]
Oh yes I am doing exactly that.
Two frames in flight and waiting on a fence before the next frame.

**Comment by Ralith** [comment]
But you only have one pair of buffers?

**Comment by GitHubJasper** [comment]
Aaaah wait, that doesn't make sense haha.
Can be so many things that it is hard to find the cause, thanks!
Going to have to change that to make sure, but that is probably it.

Glad it is not something concerning openxrs or steamvr, but just me missing stuff ;)

**Comment by GitHubJasper** [comment]
It seems to be related to that, I was actually using multiple buffer pairs but it only used the first.
Thanks for the help, I can figure it out from here!
