### ISSUE TITLE
Confusion about OpenGL session creation on Windows

### ISSUE THREAD

**Issue by NickDriscoll** [Ralith/openxrs#57]
With regards to session creation, Instance::create_session() takes an argument that represents the session create info for the active graphics API, but it appears the the OpenGL structure maps to the one for *nix I.E. XrGraphicsBindingOpenGLXlibKHR, whereas on Windows I think I'd need an instance of XrGraphicsBindingOpenGLWin32KHR. Maybe the crate does something to make the OpenGL enum a catch-all, but it's not clear to me how this is supposed to work. I could also just be missing something as I only started reading about OpenXR yesterday.

**Comment by Ralith** [comment]
The Windows-specific interface is only visible when targeting windows; see https://docs.rs/openxr/0.13.0/x86_64-pc-windows-msvc/openxr/opengl/enum.SessionCreateInfo.html.

**Comment by NickDriscoll** [comment]
Huh. It appears I was looking at outdated docs
https://docs.rs/openxr/0.13.0/openxr/index.html
