### ISSUE TITLE
Can't seem to obtain Time value for Action<Posef>

### ISSUE THREAD

**Issue by NickDriscoll** [Ralith/openxrs#61]
In my application, I have created an Action\<Posef\> and have obtained a Space from it by calling Action::create_space(). Now I want to locate that space within the broader tracking space with a call to Space::locate(tracking_space, time). The problem is that it doesn't seem like I'm able to obtain a time value for this Action. For Action<T: ActionInput>, there is a state() method which returns an ActionState which contains the Time that the Action was last updated, but I'm not seeing any kind of equivalent for Action\<Posef\>

I think that what I really need is some way to semantically say "right now" because I do just want the Posef at the moment locate() is called, but I can't seem to find that either.

**Comment by Ralith** [comment]
The time you almost invariably should be using is the time that the next frame will be displayed at, which is available in the return value of [`FrameWaiter::wait`](https://docs.rs/openxr/0.13.1/openxr/struct.FrameWaiter.html#method.wait). In rare cases, you might use [`Instance::now`](https://docs.rs/openxr/0.13.1/openxr/struct.Instance.html#method.now), but be aware that runtimes may not support that. Additionally, the data you receive from `Space::locate` is not "the position at this time", but rather "the best position estimate available for this time based on the information available to the runtime as of the most recent `Session::sync_actions` call".

**Comment by NickDriscoll** [comment]
What confuses me about this is that FrameWaiter::wait() blocks until rendering should begin.
How can this be used if I need controller poses for updating the game state which happens before rendering?

**Comment by Ralith** [comment]
You could update after calling `wait`, or use data from the previous frame. The OpenXR channel on the Khronos slack would be a better place to inquire about the intentions behind the spec.
