### ISSUE TITLE
How is Action<Posef>::create_space intended to be called?

### ISSUE THREAD

**Issue by sotownsend** [Ralith/openxrs#62]
Hellos,
I'm newer to rust and I tried digging through your source to get the intent of this but couldn't figure it out.

`Action<Posef>::create_space` consumes the `session` argument but this `session` argument is needed for other things -- is this intentional? And if so, how is `create_space` supposed to be called without consuming session?

Thanks

**Comment by Ralith** [comment]
`Session` implements `Clone`, so you can make as many duplicates of it as you like.
