### ISSUE TITLE
Dynamically loading a runtime does not work per spec

### ISSUE THREAD

**Issue by nwessing** [Ralith/openxrs#90]
The `Entry::load_from` function seems to be loading function pointers in a non spec compliant way.
Looking at this code:
https://github.com/Ralith/openxrs/blob/master/openxr/src/entry.rs#L67

Take a look at the documentation for runtime loading:
https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/master/specification/loader/runtime.adoc#loaderruntime-interface-negotiation

It looks to me like an openxr implementation should only export a single function `XrNegotiateRuntimeRequest ` and then this function will provide a function pointer to load the remaining symbols. 

I ran into this when trying to manually load Steam's OpenXR implementation. Running dumpbin on `vrclient_x64.dll` reveals that `xrNegotiateLoaderRuntimeInterface` is the only exported OpenXR function.

**Comment by Ralith** [comment]
Thanks for the issue! I believe there is some confusion here. An OpenXR implementation is software that conforms with [the OpenXR specification](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html). A runtime as defined in https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/master/specification/loader/runtime.adoc is not, strictly speaking, an OpenXR implementation; it is a *component* of the OpenXR implementation provided by the OpenXR loader. The document you linked is not part of the normative specification at all. As, indeed, it states explicitly:

> **This command is not a part of the OpenXR API** itself, only a **private** interface between the loader and runtimes for version 1 and higher interfaces

(emphasis added)
