### ISSUE TITLE
Wrong struct passed in vulkan example

### ISSUE THREAD

**Issue by LaylBongers** [Ralith/openxrs#93]
https://github.com/Ralith/openxrs/blob/730eb6764d003cac71ec1e4f745be7705aea7601/openxr/examples/vulkan.rs#L70

This should be instance create info instead of application info.

**Comment by Ralith** [comment]
The code is correct as written; otherwise it would not type-check. Refer to the implementation if the mechanism is unclear.

**Comment by LaylBongers** [comment]
Ah my bad, I read over things too fast tracking down the source of an issue
